language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kgprojs/docker-react -f Dockerfile.dev .

script:
    - ocker run -e CI=true kgprojs/docker-react npm run test


